export const GET_FOODS_SUCCESS = "GET_FOODS_SUCCESS";
export const GET_FOODS_FAIL = "GET_FOODS_FAIL";
export const GET_FOODS = "GET_FOODS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_REQ = "SIGNUP_REQ";
export const RESET_USER_REGISTERATION = "RESET_USER_REGISTERATION";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNIN_REQ = "SIGNIN_REQ";
export const SIGNIN_RESET = "SIGNIN_RESET";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_CART_REQ = "GET_CART_REQ";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_QUANTITY = "SET_QUANTITY";
export const CART_RESET = "CART_RESET";

export const ORDER_FOOD_REQ = "ORDER_FOOD_REQ";
export const ORDER_FOOD_SUCCES = "ORDER_FOOD_SUCCES";
export const ORDER_FOOD_FAIL = "ORDER_FOOD_FAIL";
export const ORDER_FOOD_RESET = "ORDER_FOOD_RESET";

// CRUD
export const ADD_FOOD_REQ = "ADD_FOOD_REQ";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
export const ADD_FOOD_FAIL = "ADD_FOOD_FAIL";

export const UPDATE_FOOD_REQ = "UPDATE_FOOD_REQ";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const UPDATE_FOOD_FAIL = "UPDATE_FOOD_FAIL";

export const DELETE_FOOD_REQ = "DELETE_FOOD_REQ";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_FAIL = "DELETE_FOOD_FAIL";

export const CRUD_FOOD_RESET = "CRUD_FOOD_RESET";

// BOOKING TABLE
export const BOOKING_TABLE_REQ = "BOOKING_TABLE_REQ";
export const BOOKING_TABLE_SUCCESS = "BOOKING_TABLE_SUCCESS";
export const BOOKING_TABLE_FAIL = "BOOKING_TABLE_FAIL";
export const BOOKING_TABLE_RESET = "BOOKING_TABLE_RESET";

// // GET PLACES
// export const GET_PLACES_REQ = "GET_PLACES_REQ";
// export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
// export const GET_PLACES_FAIL = "GET_PLACES_FAIL";
